# Generated by Django 2.0.4 on 2018-07-10 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0003_restaurant_logo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Article',
        ),
    ]
